version: '3.2'

services:
  # Slackin for Developers Italia
  developers-italia-slackin:
    container_name: developers-italia-slackin
    image: italia/developers-italia-slackin:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - overlay

networks:
  overlay:
